FROM ubuntu
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install iputils-ping -y
RUN apt-get install net-tools -y
RUN apt-get install php -y
RUN apt-get install php7.4-fpm -y

# RUN apk add nano
# # RUN echo "open_basedir = /myApp/www/html/Application/" >> /etc/php/8.0/cli/php.ini
# RUN php -S localhost:9000
# FROM php:7.4-fpm