version: '3.9'

services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../Application:/myApp/www/html/Application/
    ports:
      - '9000:80'
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - ../Application:/myApp/www/html/Application/
    deploy:
      mode: replicated
      replicas: 1
